;;;; 9ML-ivp-mlton.import.scm - GENERATED BY CHICKEN 4.8.0rc4 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only files make-pathname pathname-directory pathname-file)
         (only data-structures conc alist-ref intersperse)
         (only srfi-13 string-concatenate)
         make
         datatype
         signal-diagram
         9ML-eval
         setup-api))
(##sys#register-compiled-module
  '9ML-ivp-mlton
  (list)
  '((ivp-mlton . 9ML-ivp-mlton#ivp-mlton)
    (mlton-initial . 9ML-ivp-mlton#mlton-initial))
  (list)
  (list))

;; END OF FILE
