;;;; 9ML-parse.import.scm - GENERATED BY CHICKEN 4.8.0rc4 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only srfi-1
               fold
               combine
               every
               unzip2
               filter-map
               partition
               delete-duplicates
               cons*)
         (only srfi-13 string-null?)
         (only data-structures conc ->string)
         (only extras fprintf)
         matchable
         sxpath
         sxpath-lolevel
         static-modules
         miniML
         miniMLsyntax
         (prefix sxml-transforms sxml:)
         lalr-driver
         lalr-driver))
(##sys#register-compiled-module
  '9ML-parse
  (list)
  '((parse . 9ML-parse#parse)
    (parse-sexpr-macro . 9ML-parse#parse-sexpr-macro)
    (parse-string-expr . 9ML-parse#parse-string-expr)
    (parse-sym-expr . 9ML-parse#parse-sym-expr)
    (nineml-xmlns . 9ML-parse#nineml-xmlns)
    (parse-al-sxml-component . 9ML-parse#parse-al-sxml-component)
    (parse-al-sxml . 9ML-parse#parse-al-sxml))
  (list)
  (list))

;; END OF FILE
