;;;; 9ML-ivp-octave.import.scm - GENERATED BY CHICKEN 4.8.0rc4 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only extras sprintf)
         (only files
               make-pathname
               pathname-directory
               pathname-file
               absolute-pathname?)
         (only data-structures conc alist-ref intersperse ->string)
         (only posix current-directory)
         (only srfi-1 filter list-index)
         (only srfi-13 string-concatenate)
         make
         datatype
         signal-diagram
         9ML-eval
         setup-api))
(##sys#register-compiled-module
  '9ML-ivp-octave
  (list)
  '((ivp-octave . 9ML-ivp-octave#ivp-octave))
  (list)
  (list))

;; END OF FILE
